server:
  port: 8040
  
spring:
  application:
    name: gateway
  data: 
    mongodb:
      database: appointmentsystem
      host: localhost
      port: 27017
      
props:
  date-format: dd/MM/yyyy
