server:
  port: 8040
  
spring:
  application:
    name: gateway
  profiles:
    active:
    - dev
      
props:
  date-format: dd/MM/yyyy

---
spring:
  profiles: dev
mock-data:
  organization-name: Example Org
  address: Change me
  staff-name: Nastenka
  email: nastenka@mail.ru
  password: 111
  phone: 375291111111
  authorities:
  - ROLE_ADMIN
  - ROLE_USER
swagger: 
  open: false
  